### ISSUE TITLE
Reverb doesn't seem to work  

### ISSUE THREAD

**Issue by Yorgg** [atsushieno/nfluidsynth#9]
hi,

I cannot get the reverb effect to work. 
There is no difference between: `synth.SetReverb(0,0,0,0)` and `synth.SetReverb(1,1,1,1) `

Here is my code:

```c#

var settings = new NFluidsynth.Settings();
settings[ConfigurationKeys.AudioDriver].StringValue = "waveout"

var synth = new Synth(settings);
synth.LoadSoundFont(path, false);
synth.SoundFontSelect(0,1);
synth.ProgramChange(0,0);
synth.SetReverb(1,0.3,1,1);
synth.Gain = 0.7f;

var audioDriver = new AudioDriver(settings, synth);
```

I tried `dsound` and `waveout` audio drivers.     Am I missing something?  thanks!

fluidsynth:       2.1.3
OS:                  Windows10 
Environment:   Unity 
Sf2:                 [YDP grand piano](http://freepats.zenvoid.org/Piano/acoustic-grand-piano.html))

**Comment by atsushieno** [comment]
Thanks for the report, but with the following condition I don't think I can be of any help. 1) I have never used reverb directly. 2) Unity is not a platform I can verify any behaviour. 3) no idea if reverbs work on *any* soundfont, I havent used this YDP grand piano thing before.

What you can verify is to check if fluidsynth itself works that way, without .NET. Basically I have graduated .NET development and my support on .NET based projects is as long as I don't spend too much time and I don't plan to test that instead of you.

**Comment by Yorgg** [comment]
Thanks for the update.  I will close this issue and do more investigating.  
If the problem is with nfluidsynth I will reopen it.
